Repository kubernetes-sigs/minibroker, pull requests merged in 2019-06, with the labels that each got.

#32 Adjusted README.md link for svcat cli
  README.md
Labels: approved, cncf-cla: yes, lgtm

#24 Improve testing workflow
  Makefile
  README.md
  hack/create-cluster.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#33 Add f0rmiga as approver to OWNERS
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#35 Change import names to match repository
  .travis.yml
  Makefile
  build/build-image/Dockerfile
  charts/wordpress/README.md
  cmd/minibroker/main.go
  pkg/broker/broker.go
  pkg/minibroker/minibroker.go
  pkg/minibroker/postgres.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#36 OWNERS: add mook-as to approvers
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS
