Repository kubernetes-sigs/minibroker, pull requests merged in 2020-06, with the labels that each got.

#65 fix: no cluster admin
  .travis.yml
  Makefile
  charts/minibroker/templates/rbac.yaml
  charts/minibroker/values.yaml
  ci/test_integration.sh
  hack/create-cluster.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#66 test: Add assertions for the mysql testcase
  tests/integration/minibroker_test.go
  tests/integration/resources/mysql_client.tmpl.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#70 fix: bump Travis timeout
  ci/test_integration.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#64 refactor: shared labels template
  charts/minibroker/templates/_helpers.tpl
  charts/minibroker/templates/broker.yaml
  charts/minibroker/templates/deployment.yaml
  charts/minibroker/templates/rbac.yaml
  charts/minibroker/templates/service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#67 test: Add assertions for the mongodb testcase
  tests/integration/minibroker_test.go
  tests/integration/resources/mongodb_client.tmpl.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#69 test: Add assertions for the redis testcase
  tests/integration/minibroker_test.go
  tests/integration/resources/redis_client.tmpl.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#68 test: Add assertions for the postgresql testcase
  tests/integration/minibroker_test.go
  tests/integration/resources/postgresql_client.tmpl.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#71 feat: add dumb-init
  charts/minibroker/templates/deployment.yaml
  image/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#73 fix: remove hardcoded cluster domains
  README.md
  charts/minibroker/templates/broker.yaml
  pkg/minibroker/provider.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#75 fix: Do not run as root, use read-only filesystem
  build/image.sh
  charts/minibroker/templates/deployment.yaml
  docker/Dockerfile
  docker/rootfs/etc/passwd
  docker/rootfs/home/minibroker/tmp/.gitkeep
Labels: approved, cncf-cla: yes, lgtm, size/S
