Repository kubernetes-sigs/minibroker, pull requests merged in 2020-07, with the labels that each got.

#76 refactor: improve timeouts for integration tests
  .travis.yml
  tests/integration/README.md
  tests/integration/minibroker_test.go
  tests/integration/testutil/testutil.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#78 bump: integration tests timeout on CI
  ci/test_integration.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#74 update wordpress deployment
  charts/wordpress/templates/deployment.yaml
  charts/wordpress/templates/mysql-instance.yaml
  charts/wordpress/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#81 feat: deployment readiness and liveness probes
  build/deploy.sh
  charts/minibroker/templates/broker.yaml
  charts/minibroker/templates/deployment.yaml
  charts/minibroker/templates/service.yaml
  charts/minibroker/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#83 fix: README.md to reflect latest changes
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#82 feat: Add support for deploying rabbitmq
  README.md
  pkg/minibroker/minibroker.go
  pkg/minibroker/rabbitmq.go
  tests/integration/minibroker_test.go
  tests/integration/resources/rabbitmq_client.tmpl.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#88 fix: git tags on CI and improved dev targets
  .travis.yml
  Makefile
  build/version.sh
  ci/test_integration.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#86 fix: release regex tag matching
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#87 feat: add CI badge to README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#91 fix: CI conditions
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#90 test: Move wordpress test to the integration test suite
  Makefile
  tests/integration/consumer_test.go
  tests/integration/testutil/helm.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#92 fix: protocol names on bind credentials
  pkg/minibroker/mariadb.go
  pkg/minibroker/mongodb.go
  pkg/minibroker/mysql.go
  pkg/minibroker/postgres.go
  pkg/minibroker/redis.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#94 fix: pg logic when db and user is provided
  pkg/minibroker/postgres.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#96 refactor: make the pg logic clearer
  pkg/minibroker/postgres.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#95 feat: deploy Minibroker for Cloud Foundry
  Makefile
  build/deploy.sh
Labels: approved, cncf-cla: yes, lgtm, size/S
