Repository kubernetes-sigs/minibroker, pull requests merged in 2020-08, with the labels that each got.

#97 fix: support username set during provisioning
  pkg/minibroker/rabbitmq.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#98 fix: unchecked type assertions
  pkg/minibroker/mariadb.go
  pkg/minibroker/mongodb.go
  pkg/minibroker/mysql.go
  pkg/minibroker/postgres.go
  pkg/minibroker/rabbitmq.go
  pkg/minibroker/redis.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#102 feat: expose Dockerfile ARGs to make target
  Makefile
  build/image.sh
  docker/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/M

#103 feat: use scratch as a base for the final image
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#104 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#99 refactor: improve Provider logic
  pkg/broker/broker.go
  pkg/broker/broker_test.go
  pkg/broker/mocks/mock_broker.go
  pkg/minibroker/mariadb.go
  pkg/minibroker/minibroker.go
  pkg/minibroker/minibroker_test.go
  pkg/minibroker/mongodb.go
  pkg/minibroker/mysql.go
  pkg/minibroker/postgres.go
  pkg/minibroker/provider.go
  pkg/minibroker/provider_test.go
  pkg/minibroker/rabbitmq.go
  pkg/minibroker/redis.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL
